site_name: autodl-irssi
repo_name: autodl-irssi
repo_url: https://github.com/autodl-community/autodl-irssi

theme:
  name: material
  palette:
    primary: blue
    accent: deep orange
  author:
    github: autodl-community

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.nl2br
  - markdown.extensions.sane_lists
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: thebigmunch
      repo: audio-metadata
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - FAQ: faq.md
  - Installation: installation.md
  - Configuration:
    - Overview: configuration/overview.md
    - Options: configuration/options.md
    - Actions: configuration/actions.md
    - IRC: configuration/irc.md
    - Server: configuration/server.md
    - Channel: configuration/channel.md
    - Tracker: configuration/tracker.md
    - Filter: configuration/filter.md
    - WebUI: configuration/webui.md
    - FTP: configuration/ftp.md
  - Changelog: changelog.md
